### ISSUE TITLE
Extra frames show up when using `split-video` with ffmpeg

### ISSUE THREAD

**Issue by amvscenes** [Breakthrough/PySceneDetect#159]
As the title: i don't get good cuts. But often the scenes start or end with the previous or next scene.

I'm using a standard: detect-content split-video.

It's happening with different sources.

python source: https://www.python.org/ftp/python/3.8.2/python-3.8.2.exe
pyscenedetect source: pip install scenedetect[opencv,progress_bar]
ffmpeg source: https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20200415-51db0a4-win64-static.zip

Here the debug command output:
[debug.txt](https://github.com/Breakthrough/PySceneDetect/files/4480305/debug.txt)

**Comment by amvscenes** [comment]
Here a sample: https://gofile.io/?c=pf6fAV

The output: https://gofile.io/?c=DuSWBq

**Comment by amvscenes** [comment]
Using mkvmerge is fine. I only added "-c".

**Comment by Breakthrough** [comment]
I was hoping this would go away after closing out #93, but it appears that it's still cropping up.  I can try shifting the start time ahead by 1 frame, but then you might miss a frame or two on other scenes.  Still not sure what the root cause is of this.

I may close this as a duplicate of #93 and reopen it.  To investigate the fix, I was going to try and use frame numbers with ffmpeg instead of timecodes - still unsure as of why the issue is occuring, however, as outputting actual images of the frames it's using as timecodes seems to line up with what is expected.

Thoughts?

**Comment by Breakthrough** [comment]
@amvscenes Does the issue show up in the actual video frames, or just the thumbnail?  I took a quick glance at the output you sent and didn't immediately see anything wrong.  How should I be validating what you're seeing?  (Extracting all frames to images?)

**Comment by amvscenes** [comment]
I can see that when playing it and if i analyze it into a movie editor.

If you export all frames you see that the split contain two scenes instead of one.

scene 03
![immagine](https://user-images.githubusercontent.com/63712650/79431575-ecbaae00-7fca-11ea-92cf-f4b30ce4c7a7.png)
scene 04
![immagine](https://user-images.githubusercontent.com/63712650/79431588-f17f6200-7fca-11ea-87ca-565e892c4cd9.png)

I removed frames in between to show the issue.

**Comment by Breakthrough** [comment]
Thanks for the response.  Last thing for now then, if you use the `save-images` command, are the first/last frames that PySceneDetect extracts correct?

I'm still not entirely sure what the underlying issue is here, because the timecodes passed to both mkvmerge and ffmpeg are the same in both cases...  I'll try to see if I can get to the bottom of this though, hoping there's a way I can get ffmpeg to produce frame-perfect cuts without too much trouble.  Thanks for the data.

**Comment by amvscenes** [comment]
Yes. The save-images output is perfect.

![immagine](https://user-images.githubusercontent.com/63712650/79632606-b020bb00-8160-11ea-9a92-eb5067db110b.png)

**Comment by Breakthrough** [comment]
Hey @amvscenes;

So I did some further digging here, and noticed something interesting - when re-encoding the file with ffmpeg, the framerate seems to double for some reason?  Also the framerate of the original video is a rather odd number, can you confirm that it is correct?

I'm able to replicate this issue on my end, but not sure exactly how to proceed.  I was able to get frame-accurate cuts by manually specifying -frames to `ffmpeg`, but ffmpeg thinks the framerate is actually 47.9fps (twice the input), whereas both OpenCV and vlc indicate that the original framerate is 23.9-something FPS.  Thus, the frame length I would calculate would be completely wrong (since the output seems to have twice the number of frames).  I'll investigate if forcing the output framerate would be an acceptable workaround, since it seems like there is indeed duplicate frames in the output in this particular case, although why that is I'll need your help to solve.

You mentioned this happens with different sources, do they all share the same framerate/codec?  Have you noticed the doubling in framerate in the output?  Generally issues like that can be caused by corrupted video files, although since you mentioned this happens with several sources, I'd like to dig a little further into that and see if there is any commonalities between those sources (specifically how they were encoded).

**Comment by Breakthrough** [comment]
Hey again @amvscenes;

Would you be able to provide a longer clip?  It seems like the actual timestamps get skewed over time in this particular case, and specifying a framerate override doesn't seem to help.  I did fix an issue where the end timestamp could select an extra frame (pushed to master), but here it seems like over time, the actual timestamps need to be shifted backwards.

I'm not entirely sure why this is happening here, but given ffmpeg's misinterpretation of the framerate, something suspicious is definitely going on here.  Additional samples and any other information you can provide would be most helpful.

**Comment by Breakthrough** [comment]
Sorry for the comment spam, this issue has been driving me crazy.  It seems like the original video you provided either has a variable framerate, or something is wrong with the way ffmpeg is decoding the codec.  Supplying `-vsync 0` to `ffmpeg` changes the framerate to 24.something FPS from the original value.

That being said, I was able to yield acceptable output by supplying `-r {VIDEO_FPS} -vsync 0`, although ffmpeg does give a warning for that.  Would you be able to see if adding that resolves the issue you're seeing?  The command you can use to verify this on your end is:

    scenedetect -i sample.m4v detect-content split-video -a "-r 23.927353 -vsync 0"

Where 23.927353 is the framerate of the sample.m4v file you provided.  If the above command resolves this issue, I'll look into adding an option to automatically add those settings (e.g. `--framerate-override`), or determine if I can detect a discrepency in the framerate that ffmpeg detects versus the original video, and somehow apply the option automatically.

If you do get positive results with the above command, can you also try it on a few other videos to make sure it indeed resolves the issue you're seeing?  Thank you!

**Comment by amvscenes** [comment]
So that command works fine on the sample. The cuts seem right.
As sources I tested other japan television series that probably have the same enconding.

Thank you for noticing that the sample is weird. I discovered that it's fault of the extractor that I used which was handbrake.
Here a sample extracted with mkvmerge: https://gofile.io/?c=prFFXF

It does give out different output with this sample, but it kinda have the same issue.
Your command fix even the new sample.

**Comment by amvscenes** [comment]
So, I tested with an american live action series and I have the same issue.

It seems that in front or end of each split there is a next or previous scene frame, freezed for sometime.

Since it's still 23.976 fps I tried your command and it fixed even on that source.

They are coming from different places with different encoding settings. So I don't think it's a source issue but a general one.

Also, it doesn't only fix the cut, it also let mpc show a correct lenght while playing. With the wrong cut versions, it's like mpc doesn't know how long they are and when they will finish.

**Comment by Breakthrough** [comment]
Gotcha, I'll have to keep experimenting with the command line options then to make sure this doesn't break anything else.  Would you be able to provide me another sample I can use for testing?  (you can [leave a comment here](http://bcastell.com/contact/) if you'd prefer to not post it publicly)

Ideally I'd like to have a small collection of videos I can use for automatic testing to make sure the cuts from ffmpeg line up with the ones from `save-images`, to make sure any changes I make really do solve the issue.  Thanks again for your help.

**Comment by amvscenes** [comment]
Here 2 minutes extracted at half episode of one anime and one live action: https://gofile.io/?c=hPbOy3

**Comment by jelias** [comment]
I realized the last comment is only 2 days old, but wanted to jump in that I am having the same issue with FFmpeg, haven't tested mkv yet (was hoping for mp4 outputs). 

Running on MacOS, FFmpeg 4.2.1. 

The clip is 29.97 FPS, would I just add a similar line to what is suggested above ```"-r 23.927353 -vsync 0"``` but with the correct frame rate? ie ```"-r 29.97 -vsync 0"```

**Comment by joshcoales** [comment]
Hi, thought I might be able to add another data point here, running PySceneDetect on a linux system. I've split up a video into scenes and stats, with images and video. It's all zipped up here:
https://mega.nz/file/vPgRkQgA
Using this video:
https://www.youtube.com/watch?v=oKiF45RBfHg
- In windows default video player, "Films & TV", the sound doesn't start for a few seconds after the clip starting when first opening, it actually skips forward a couple seconds, to start playing video when the sound starts. Then there are 5 seconds of sound with the frozen final frame of the scene at the end of the video.
- Playing in VLC, it seems to work fine.
- In windows photo viewer, no sound for 3/4 seconds at the start, and at the end there are 2-3 seconds of sound with the first frame of the next scene, frozen.
- Playing in telegram desktop's media player, the final frame shows as the next scene.
- Playing in telegram mobile's media player, the final 2 seconds are the first frame of the next scene frozen.

**Comment by joshcoales** [comment]
This might or not be related, but in video_splitter.py, lines 235 to 238:
https://github.com/Breakthrough/PySceneDetect/blob/e1ee8e3d95fc025c12973ce985eb73ff8c488c81/scenedetect/video_splitter.py#L235-L238

What are the `-strict` and `-2` arguments? I don't see them anywhere in the ffmpeg docs: https://ffmpeg.org/ffmpeg.html

Also, why are you using `-t` and calculating duration yourself, rather than using `-to` and specifying the end timecode?

Looks like the rest makes sense:
- `-y` overwrite without asking
- `-ss` start time
- `-i` input file
- `-sn` skip copying subtitles

But those 3 confused me a bit, I'm not sure whether swapping `-t` for `-to` might fix your problem, but it's gotten a bit later than I expected here so I can't investigate it myself today.

**Comment by Breakthrough** [comment]
@jelias Can you share any of the media you're using to add to the test suite?

@joshcoales Sorry I'm also a bit tied up at the moment, but this is definitely the highest prirority issue for PySceneDetect currently - will be looking to schedule some time in the coming months to address this, so thank you for your addional test cases.  Any additional information you can glean/investigate in the meantime will be much appreciated.

Thank you all, and sorry I've been so busy with IRL stuff lately!

**Comment by joshcoales** [comment]
No worries at all! Life is a bit crazy right now for a lot of us, it's very understandable! I hope to be able to investigate some more tomorrow, but thank you loads for creating this library

**Comment by joshcoales** [comment]
I've filed a PR now which should fix this, by moving start timecode after input specification, and moving end timecode a frame earlier.
https://github.com/Breakthrough/PySceneDetect/pull/166

**Comment by jelias** [comment]
@Breakthrough Sorry I didn't get back to you sooner. Yes! You can [download the clips here](https://www.dropbox.com/s/kcf5lfu3qd1n97m/SceneDetect-Testing.zip?dl=0). 

@joshcoales Hopefully the PR goes through! Do you know if there would be a workaround for the current version? Trying to split a few files tomorrow and worried about hitting this blocker again.. Would there be a way to add a flag in the terminal line? 
Or would the solution be build from your src?

**Comment by joshcoales** [comment]
I don't think there's a workaround without going in and editing the video splitter file in the installed package. The arguments passed to ffmpeg are in an order ffmpeg doesn't like.

A temporary workaround, until the PR is merged, is to uninstall the package and install the version from my branch, like so:
```
pip uninstall scenedetect
pip install git+https://github.com/joshcoales/PySceneDetect.git@cut-video-without-final-frame
```
But you'll want to uninstall and reinstall from master once it's merged

**Comment by Breakthrough** [comment]
Will be working on adding integration/unit tests for this issue next week so that once a fix has been implemented, regressions can be prevented.  This is still happening on master unfortunately, but will be spending some time to hopefully correct all remaining instances of this issue this upcoming week.

Many thanks to @joshcoales for his help on this (esp #166), looking forward to finally stomping this one out for good.

**Comment by Breakthrough** [comment]
@jelias Do you recall which of these files gave you the most problems?  Would like to pick a good example to add as an integration test - am having trouble replicating the issue locally again, so want to know exactly which produced incorrect results on your end; thanks!

**Comment by Breakthrough** [comment]
@jelias Sorry for sounding like a broken record, I was thinking I found it but it seems like I'm still unable to replicate this on my end.  Which tool are you using to verify the output of PySceneDetect with?

If I copy the audio stream, the resulting length reported by VLC is incorrect, but manually decoding frame-by-frame using OpenCV still shows the last frame as lining up with what was expected.  Re-encoding the audio results in VLC reporting the correct length.  I'm unable to extract any frames that are outside of the expected scene, however.

**Comment by Breakthrough** [comment]
@amvscenes Could you provide me a live action example again?  Sorry I wasn't able to follow up on this until now.
 
I did some more experimenting on the source you provided, and for some reason, if I re-encode it before providing it to PySceneDetect, the correct output appears.  Something weird is happening with that particular source file, where the framerate ffmpeg detects is different than what it actually plays back at.

**Comment by jelias** [comment]
hey @Breakthrough! No, not sounding like a broken record, sorry I've been AFK for a bit but just caught these. I will try to go through my files in the next few days to find a good example (happy to provide original and split). In terms of verification, I've been either viewing the clips in VLC or dropping them directly into Premiere Pro—I think that's what you mean?

Running ffmpeg v. 4.2.1, PySceneDetect v0.5.2

**Comment by jelias** [comment]
Shame on me. Here are those files finally.. 

https://drive.google.com/file/d/1AVO1OTPqCoVraepnpfVDGvYUvBO1F5jY/view?usp=sharing

`Note, this link will be broken after December 2020`

**Comment by Breakthrough** [comment]
Haha thank you!!  When I saw the title of the issue in my inbox my initial reaction was "oh no, not again..." lol, thank you for this being a good comment.  This is incredibly valuable for any further regressions, much appreciated.  This is exactly what I needed to develop an integration test for this sort of thing.

Have you tested the latest release on your machine out of curiosity?

**Comment by jelias** [comment]
Hahaha oh no, I know that exact feeling. The Github Issues emails 😰. I have not no, I'll try to play around it this week if I can. Probably time to run some updates anyway...

**Comment by donghoonlee20** [comment]
I get this issue again, using the latest version

**Comment by Breakthrough** [comment]
@donghoonlee20 does it happen even if you re-do the file container with `ffmpeg` using `-c:v copy`?
